---
name: Prek auto-update

on:
  schedule:
    - cron: "0 7 * * 1"

permissions: {}


jobs:
  auto-update:
    name: Prek auto-update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: true
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: 3.12
      - name: Install prek
        uses: j178/prek-action@53276d8b0d10f8b6672aa85b4588c6921d0370cc  # v2.0.1
        with:
          install-only: true
      - name: Run prek autoupdate
        run: prek auto-update --freeze --cooldown-days 7
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1  # v8.1.1
        with:
          body: |
            Update versions of tools in pre-commit configs to latest version
          branch: chore/prek-autoupdate
          commit-message: "chore(prek): auto-update hooks"
          labels: dependencies
          title: Auto-update pre-commit hooks
          token: ${{ secrets.GITHUB_TOKEN }}
